# Generated by Django 5.0.3 on 2024-03-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('normal', 'Нормальный'), ('urgent', 'Срочный'), ('backlog', 'Бэклог')], default='normal', max_length=20),
        ),
    ]
