# Generated by Django 5.0.3 on 2024-03-18 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
