# Generated by Django 5.0.3 on 2024-03-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_task_due_date_task_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='start_date',
        ),
    ]
